services:
  - type: web
    name: edusec
    plan: free
    env: docker
    repo: https://github.com/Athar-3/srujanfoundations.git
    region: India
    envVars:
      - key: DATABASE_URL
        value: "mysql://shkathar:yourpassword@sql.freedb.tech/freedb_srujandb"


